apiVersion: apps/v1
kind: Deployment
metadata:
name: hello
labels:
  app: hello
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello
        tier: hello
  spec:
    containers:
    - name: hello
      image: anggit/hello:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 8080
        name: hello

---
apiVersion: v1
kind: Service
metadata:
name: hello
labels:
  app: hello
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: hello
    tier: hello
type: LoadBalancer
